[package]
name = "wave_forge"
version = "0.1.0"
edition = "2021"

[dependencies]
wave-forge-app = { path = "wave-forge-app" }
anyhow = "1.0"

[workspace]
members = [
    "wfc-core",
    "wfc-rules",
    "wfc-gpu",
    "wave-forge-app",
]

[workspace.dependencies]
# Add common dependencies here if needed later

[profile.release]
lto = true
strip = true
codegen-units = 1

[workspace.lints.clippy]
restriction = "warn"
pedantic = "warn"
nursery = "warn"
