# Clippy configuration file.
# Lints are generally configured via Cargo.toml [lints.clippy] or command-line arguments.

# Enable stricter lint groups

# Pedantic lints: Generally useful but potentially noisy style suggestions

# Nursery lints: New lints that are still being tested

# You can add more specific configurations below if needed.
# For example, to allow a specific pedantic lint:
# allow = ["clippy::must_use_candidate"] 