@echo off
echo Running tests for core packages...
echo Testing wfc-core...
cargo test -p wfc-core
echo Testing wfc-rules...
cargo test -p wfc-rules
echo Testing wfc-gpu (non-GPU tests only)...
cargo test -p wfc-gpu -- --skip test_gpu 