[package]
name = "wave-forge-app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wave-forge"
path = "src/main.rs"

[dependencies]
wfc-core = { path = "../wfc-core" }
wfc-rules = { path = "../wfc-rules" }
wfc-gpu = { path = "../wfc-gpu", optional = true }

clap = { version = "4.4", features = ["derive"] }
rayon = "1.8"
log = "0.4"
env_logger = "0.11"
anyhow = "1.0" # For application-level error handling
humantime = "2.1" # For parsing duration strings
tokio = { version = "1", features = ["full"] } # Add tokio for async runtime

[features]
default = []
gpu = ["dep:wfc-gpu"]

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
tempfile = "3.8" 