[package]
name = "wfc-rules"
version = "0.1.0"
edition = "2021"
rust-version = "1.98"

[dependencies]
log = "0.4.34"
thiserror = "2.0.20"
serde = { version = "1.0.229", features = ["derive"], optional = true }
serde_json = { version = "1.0.151", optional = true }
ron = "0.12.2"        # Example, could use JSON instead

[dev-dependencies]
proptest = "1.11.0"

[features]
default = ["serde"]
serde = ["dep:serde", "dep:serde_json"]