[package]
name = "wfc-gpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.19" # Check for latest stable wgpu version
wfc-core = { path = "../wfc-core" }
thiserror = "1.0"
log = "0.4"
bytemuck = { version = "1.15", features = ["derive"] }
bitvec = "1.0"
futures-intrusive = "0.5" # For async buffer mapping

[dev-dependencies] 