//! A pack: the stages a world is generated by, as a file names them.
//!
//! A pack is RON: a version, a list of named stages and a list of named tables of facts. A stage
//! reads other stages by name, and how far it reads follows from its parameters (a blur's radius),
//! so a pack never states a reach by hand. Loading checks everything that can be checked before
//! generating: the version, unknown and duplicate names, parameters out of range, what each
//! expression may read where it is evaluated, and cycles, each error naming the stage or table.

use crate::towns::Selector;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

/// The pack format this library reads.
pub const PACK_VERSION: u32 = 1;

/// A pack as written in a file.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct PackFile {
    pub version: u32,
    /// The stages in the order a stack shows them; a stage may read any other, earlier or later.
    pub stages: Vec<StageDef>,
    /// Tables of facts: rows the game gives, and rows generated from a parent table's.
    #[serde(default)]
    pub tables: Vec<TableDef>,
}

/// A table of facts: rows the game gives, or rows generated from the pack, the seed and a parent
/// table's rows. Expressions read a table through the row a runtime is focused on
/// ([`Expr::Row`]).
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TableDef {
    pub name: String,
    pub kind: TableKind,
}

/// Where a table's rows come from.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub enum TableKind {
    /// Rows the game gives at run time ([`crate::stages::Facts::give`]), each with the game's own
    /// id and a value for every column: a history's villages, say.
    Given { columns: Vec<(String, Column)> },
    /// Rows computed from the seed: for each row of `parent`, or once without a parent, `count`
    /// rows, each column's value from its expression. The expressions read the parent row
    /// ([`Expr::Parent`]), the row's own hash stream ([`Expr::Random`]), its place among its
    /// siblings ([`Expr::Index`], [`Expr::Count`]) and a share of a parent's budget
    /// ([`Expr::Share`]). A row's id is its parent's id and its index, so rows never shift when
    /// other parents' children change.
    Generated {
        #[serde(default)]
        parent: Option<String>,
        count: Expr,
        columns: Vec<(String, Expr)>,
    },
}

/// What a given table's column holds. Every value is a number to the expressions that read it; a
/// name is its index in the list.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub enum Column {
    Number,
    /// One of these names.
    Names(Vec<String>),
}

/// The most rows a generated table may have for one parent row, or in all without a parent.
pub const MAX_CHILDREN: u32 = 65_536;

/// One stage of a pack.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct StageDef {
    pub name: String,
    /// How many of the WFC lattice's cells one of the stage's columns spans along each axis: 1, the
    /// default, for the finest level, more for a coarse one, a world map's say. A stage's chunks
    /// have the same number of columns at every scale, so a coarse stage's chunk covers more
    /// ground. Stages read only stages as coarse as themselves or coarser.
    #[serde(default = "base_scale")]
    pub scale: u32,
    pub kind: StageKind,
}

const fn base_scale() -> u32 {
    1
}

/// What a stage does.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub enum StageKind {
    /// A value per cell column, computed from an expression at that column alone.
    Field(Expr),
    /// A category per cell column: the first of `rules` whose conditions all hold there, or
    /// `otherwise`. The categories are the names the rules give, in the order they first appear,
    /// then `otherwise`'s.
    Rules { rules: Vec<Rule>, otherwise: String },
    /// Another field averaged over the square of `radius` cells around each column.
    Blur { input: String, radius: u32 },
    /// The highest value of another field less its lowest over the square of `radius` cells around
    /// each column: how uneven the ground is there, what Valheim calls terrain delta.
    Delta { input: String, radius: u32 },
    /// Where each column lies in its category of a Rules stage: `edge` where any of the eight
    /// columns `distance` cells away, along the axes and the diagonals, has another category, and
    /// `median` elsewhere, as Valheim's biome area tells the two apart.
    Area { input: String, distance: u32 },
    /// Settlement sites: rectangles of whole chunks, at most one per square region of `region`
    /// chunks, placed with `chance`, between `size.0` and `size.1` chunks on a side, and kept at
    /// least one chunk inside their region, so two sites are always two chunks apart. Each site's
    /// height is the mean of the `height` field over its footprint's centre and inner corners.
    Sites {
        height: String,
        region: u32,
        size: (u32, u32),
        chance: f32,
    },
    /// A settlement site for every row of the table `table`: a square of whole chunks around the
    /// chunk that holds the row's position, which the columns `at` give in WFC cells, as many
    /// chunks on a side as its `size` column says, a whole number from 1 to `max_size`. Each
    /// site's height is found as a Sites stage finds it. Giving the runtime facts
    /// ([`crate::stages::Runtime::set_facts`]) refuses rows whose sites would come within a chunk
    /// of each other, as a Sites stage's never do.
    TableSites {
        table: String,
        height: String,
        at: (String, String),
        size: String,
        max_size: u32,
    },
    /// The `height` field levelled to each of `sites`' heights inside its footprint and blended
    /// back to the field over `blend` cells around it.
    Flatten {
        height: String,
        sites: String,
        blend: u32,
    },
    /// A town on each of `sites`: a bounded WFC world of the rule set named `rules`, the size of
    /// the site's footprint, solved whole, with `bottom` on its lowest layer and `top` on its
    /// highest. With `by`, sites from a table choose their rule set by a names column of their
    /// row: `(column, [(name, rules), ...])`, and a name the list does not give takes `rules`.
    Solve {
        sites: String,
        rules: String,
        #[serde(default)]
        by: Option<(String, Vec<(String, String)>)>,
        #[serde(default)]
        bottom: Option<Selector>,
        #[serde(default)]
        top: Option<Selector>,
    },
    /// Curves a region job computes over a whole square region of `region` chunks at a time, from
    /// its `inputs` over the region and `halo` chunks around it: rivers, roads, anything one chunk
    /// cannot see. `job` names the Rust implementation the runtime was given
    /// ([`crate::stages::Runtime::with_region_job`]); it may reject an attempt and is retried with a
    /// new hash stream up to `budget` times. A chunk's product is the curves that pass through it.
    Region {
        job: String,
        region: u32,
        #[serde(default)]
        halo: u32,
        #[serde(default)]
        inputs: Vec<String>,
        #[serde(default = "one_attempt")]
        budget: u32,
    },
    /// A straight curve for every row of the table `table`, from the point the columns `from` give
    /// to the one `to` give, in WFC cells, with the radius its `radius` column gives at both ends:
    /// a road a history laid between two villages, say. A chunk's product is the curves that pass
    /// through it.
    TableCurves {
        table: String,
        from: (String, String),
        to: (String, String),
        radius: String,
    },
    /// The `height` field with the curves of `curves` drawn into it: within a curve's radius, the
    /// value each of its values gives, of at most `max_radius` cells, the ground takes the
    /// `profile`'s height, and it blends back to the field over `blend` cells beyond. Where curves
    /// overlap, the one that weighs most at the column wins, the first by id on a tie.
    Apply {
        height: String,
        curves: String,
        max_radius: u32,
        #[serde(default)]
        blend: u32,
        profile: Profile,
    },
    /// Points of `kind` standing on the `height` field: one candidate per square block of
    /// `spacing` cells at a hashed column inside it, kept with probability `chance`, if the height
    /// there is within `between`, the slope at most `max_slope` (height per cell), the column at
    /// least `margin` cells from every site of `avoid`, and no kept candidate of higher priority is
    /// closer than `apart` cells. That last test reads neighbours' candidates, never their
    /// results, so points keep their distance across chunk seams.
    Scatter {
        kind: String,
        height: String,
        spacing: u32,
        #[serde(default = "always")]
        chance: f32,
        #[serde(default)]
        between: Option<(f32, f32)>,
        #[serde(default)]
        max_slope: Option<f32>,
        #[serde(default)]
        avoid: Option<(String, u32)>,
        #[serde(default)]
        apart: u32,
    },
}

/// The height an Apply stage gives the ground under a curve.
#[derive(Clone, Copy, Debug, PartialEq, Deserialize, Serialize)]
pub enum Profile {
    /// The field's height at the nearest point of the curve's centre line: a road, level across.
    Level,
    /// That height lowered by a depth: a river's bed.
    Carve(f32),
}

/// One rule of a Rules stage: a category, and the conditions that all have to hold for a column to
/// take it.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct Rule {
    pub category: String,
    pub when: Vec<Condition>,
}

/// The most categories one Rules stage can name: a category is a byte per column.
pub const MAX_CATEGORIES: usize = 256;

const fn one_attempt() -> u32 {
    1
}

/// The most attempts a region job may be given.
pub const MAX_BUDGET: u32 = 1024;

const fn always() -> f32 {
    1.0
}

/// What a stage produces, which decides which stages may read it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Output {
    Field,
    Categories,
    Sites,
    Tiles,
    Points,
    Curves,
}

impl StageKind {
    /// The categories a Rules or Area stage names, in the order of their indices; none for other
    /// kinds.
    #[must_use]
    pub fn categories(&self) -> Vec<&str> {
        let (rules, otherwise) = match self {
            Self::Rules { rules, otherwise } => (rules, otherwise),
            Self::Area { .. } => return vec!["median", "edge"],
            _ => return Vec::new(),
        };
        let mut names: Vec<&str> = Vec::new();
        for name in rules
            .iter()
            .map(|rule| rule.category.as_str())
            .chain([otherwise.as_str()])
        {
            if !names.contains(&name) {
                names.push(name);
            }
        }
        names
    }

    pub(crate) const fn output(&self) -> Output {
        match self {
            Self::Field(_)
            | Self::Blur { .. }
            | Self::Delta { .. }
            | Self::Flatten { .. }
            | Self::Apply { .. } => Output::Field,
            Self::Rules { .. } | Self::Area { .. } => Output::Categories,
            Self::Region { .. } | Self::TableCurves { .. } => Output::Curves,
            Self::Sites { .. } | Self::TableSites { .. } => Output::Sites,
            Self::Solve { .. } => Output::Tiles,
            Self::Scatter { .. } => Output::Points,
        }
    }
}

/// How far beyond its chunk a stage reads an input: in cells, or in whole chunks, which the
/// runtime turns into cells once it knows how large a chunk is.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Reach {
    Cells(u32),
    Chunks(u32),
}

impl Reach {
    /// The reach in cells along each lattice axis, for chunks of `size` cells.
    pub(crate) const fn cells(self, size: [u32; 2]) -> [u32; 2] {
        match self {
            Self::Cells(cells) => [cells, cells],
            Self::Chunks(chunks) => [chunks * size[0], chunks * size[1]],
        }
    }
}

/// A field's value at one cell column.
///
/// Coordinates are in cells, measured from the world's origin to the centre of the column, with
/// the lattice's x and y.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub enum Expr {
    Constant(f32),
    /// Value noise in 0..1: `octaves` layers, the first with `frequency` lattice points per cell,
    /// each next one at twice the frequency and half the weight. A noise with a `name` draws from
    /// a stream of that name, the same in every stage that names it, so it can be read again
    /// elsewhere; one without draws from its stage's own stream, which every unnamed noise of the
    /// stage shares.
    Noise {
        frequency: f32,
        octaves: u32,
        #[serde(default)]
        name: Option<String>,
    },
    /// Another field's value at the same column.
    Input(String),
    /// The column's x and y.
    X,
    Y,
    /// How far the column is from a point, in cells.
    Distance((f32, f32)),
    /// The direction from a point to the column, as a fraction of a whole turn from +x towards
    /// +y, in 0..1.
    Angle((f32, f32)),
    Add(Box<Expr>, Box<Expr>),
    Sub(Box<Expr>, Box<Expr>),
    Mul(Box<Expr>, Box<Expr>),
    Min(Box<Expr>, Box<Expr>),
    Max(Box<Expr>, Box<Expr>),
    Abs(Box<Expr>),
    Floor(Box<Expr>),
    /// The sine of an angle in radians.
    Sin(Box<Expr>),
    /// 1 where a Rules stage's category at the column is one of the names, 0 elsewhere.
    Is(String, Vec<String>),
    /// The value, held between a low and a high bound.
    Clamp(Box<Expr>, f32, f32),
    /// 0 at or below the first edge, 1 at or above the second, and a smooth step between.
    Smoothstep(f32, f32, Box<Expr>),
    /// The value mapped linearly from one range onto another, without clamping.
    Remap(Box<Expr>, (f32, f32), (f32, f32)),
    /// A piecewise-linear curve through `(x, y)` points in increasing x, level beyond its ends.
    Curve(Box<Expr>, Vec<(f32, f32)>),
    /// A column of the row the runtime is focused on in a table
    /// ([`crate::stages::Runtime::focus`]): a planet's radius on its surface, say. Stages only.
    Row(String, String),
    /// A column of the parent row. Generated tables only.
    Parent(String),
    /// A number from `low` up to but not including `high`, from the row's own hash stream and its
    /// column's: every `Random` of one column draws the same number, spread over its own range.
    /// Generated tables only.
    Random(f32, f32),
    /// The row's place among its parent's children, from 0. Generated tables' columns only.
    Index,
    /// How many children the row's parent has. Generated tables' columns only.
    Count,
    /// The row's share of a whole-number column of its parent: the parent's value split among its
    /// children by hashed weights into whole numbers that add up to it exactly. Generated tables'
    /// columns only.
    Share(String),
    /// `then` where the condition holds, `otherwise` where it does not.
    Select {
        when: Condition,
        then: Box<Expr>,
        otherwise: Box<Expr>,
    },
    /// One expression per category of a Rules stage, blended where categories meet: each
    /// category found within `blend` cells of the column weighs in with a tent that falls from the
    /// column outwards, and a category no case names takes `otherwise`. With a `blend` of 0 it
    /// picks the column's own category's expression.
    Match {
        input: String,
        cases: Vec<(String, Expr)>,
        otherwise: Box<Expr>,
        blend: u32,
    },
}

/// The widest band a `Match` blends over, in cells: a column reads `(2 * blend + 1)^2` categories.
pub const MAX_BLEND: u32 = 32;

/// A comparison of two expressions at one column.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub enum Condition {
    Less(Box<Expr>, Box<Expr>),
    Greater(Box<Expr>, Box<Expr>),
    /// The value lies between a low and a high bound, both included.
    Between(Box<Expr>, f32, f32),
}

impl Condition {
    fn inputs<'a>(&'a self, into: &mut Vec<(&'a str, Output, u32)>) {
        match self {
            Self::Less(a, b) | Self::Greater(a, b) => {
                a.inputs(into);
                b.inputs(into);
            }
            Self::Between(a, ..) => a.inputs(into),
        }
    }

    fn check(&self) -> Result<(), String> {
        match self {
            Self::Less(a, b) | Self::Greater(a, b) => a.check().and_then(|()| b.check()),
            Self::Between(a, low, high) => {
                if !(low.is_finite() && high.is_finite() && low <= high) {
                    return Err(format!("between {low} and {high} is not a range"));
                }
                a.check()
            }
        }
    }

    /// Calls `f` on every expression inside the condition, and every expression inside those.
    fn visit(&self, f: &mut dyn FnMut(&Expr)) {
        match self {
            Self::Less(a, b) | Self::Greater(a, b) => {
                a.visit(f);
                b.visit(f);
            }
            Self::Between(a, ..) => a.visit(f),
        }
    }

    /// The categories this condition reads, with the names it expects of them.
    fn categories<'a>(&'a self, into: &mut Vec<(&'a str, Vec<&'a str>)>) {
        match self {
            Self::Less(a, b) | Self::Greater(a, b) => {
                a.categories(into);
                b.categories(into);
            }
            Self::Between(a, ..) => a.categories(into),
        }
    }
}

impl Expr {
    /// The stages this expression reads, with what it reads each as and how many cells from the
    /// column.
    fn inputs<'a>(&'a self, into: &mut Vec<(&'a str, Output, u32)>) {
        match self {
            Self::Constant(_)
            | Self::Noise { .. }
            | Self::X
            | Self::Y
            | Self::Distance(_)
            | Self::Angle(_)
            | Self::Row(..)
            | Self::Parent(_)
            | Self::Random(..)
            | Self::Index
            | Self::Count
            | Self::Share(_) => {}
            Self::Input(name) => into.push((name, Output::Field, 0)),
            Self::Is(name, _) => into.push((name, Output::Categories, 0)),
            Self::Match {
                input,
                cases,
                otherwise,
                blend,
            } => {
                into.push((input, Output::Categories, *blend));
                for (_, case) in cases {
                    case.inputs(into);
                }
                otherwise.inputs(into);
            }
            Self::Add(a, b)
            | Self::Sub(a, b)
            | Self::Mul(a, b)
            | Self::Min(a, b)
            | Self::Max(a, b) => {
                a.inputs(into);
                b.inputs(into);
            }
            Self::Abs(a)
            | Self::Floor(a)
            | Self::Sin(a)
            | Self::Clamp(a, ..)
            | Self::Smoothstep(_, _, a)
            | Self::Remap(a, ..)
            | Self::Curve(a, _) => a.inputs(into),
            Self::Select {
                when,
                then,
                otherwise,
            } => {
                when.inputs(into);
                then.inputs(into);
                otherwise.inputs(into);
            }
        }
    }

    /// Calls `f` on this expression and every expression inside it, conditions' included.
    pub(crate) fn visit(&self, f: &mut dyn FnMut(&Expr)) {
        f(self);
        match self {
            Self::Constant(_)
            | Self::Noise { .. }
            | Self::Input(_)
            | Self::X
            | Self::Y
            | Self::Distance(_)
            | Self::Angle(_)
            | Self::Is(..)
            | Self::Row(..)
            | Self::Parent(_)
            | Self::Random(..)
            | Self::Index
            | Self::Count
            | Self::Share(_) => {}
            Self::Add(a, b)
            | Self::Sub(a, b)
            | Self::Mul(a, b)
            | Self::Min(a, b)
            | Self::Max(a, b) => {
                a.visit(f);
                b.visit(f);
            }
            Self::Abs(a)
            | Self::Floor(a)
            | Self::Sin(a)
            | Self::Clamp(a, ..)
            | Self::Smoothstep(_, _, a)
            | Self::Remap(a, ..)
            | Self::Curve(a, _) => a.visit(f),
            Self::Select {
                when,
                then,
                otherwise,
            } => {
                when.visit(f);
                then.visit(f);
                otherwise.visit(f);
            }
            Self::Match {
                cases, otherwise, ..
            } => {
                for (_, case) in cases {
                    case.visit(f);
                }
                otherwise.visit(f);
            }
        }
    }

    /// The categories this expression reads, with the names it expects of them.
    fn categories<'a>(&'a self, into: &mut Vec<(&'a str, Vec<&'a str>)>) {
        match self {
            Self::Constant(_)
            | Self::Noise { .. }
            | Self::Input(_)
            | Self::X
            | Self::Y
            | Self::Distance(_)
            | Self::Angle(_)
            | Self::Row(..)
            | Self::Parent(_)
            | Self::Random(..)
            | Self::Index
            | Self::Count
            | Self::Share(_) => {}
            Self::Is(name, names) => into.push((name, names.iter().map(String::as_str).collect())),
            Self::Match {
                input,
                cases,
                otherwise,
                ..
            } => {
                into.push((input, cases.iter().map(|(name, _)| name.as_str()).collect()));
                for (_, case) in cases {
                    case.categories(into);
                }
                otherwise.categories(into);
            }
            Self::Add(a, b)
            | Self::Sub(a, b)
            | Self::Mul(a, b)
            | Self::Min(a, b)
            | Self::Max(a, b) => {
                a.categories(into);
                b.categories(into);
            }
            Self::Abs(a)
            | Self::Floor(a)
            | Self::Sin(a)
            | Self::Clamp(a, ..)
            | Self::Smoothstep(_, _, a)
            | Self::Remap(a, ..)
            | Self::Curve(a, _) => a.categories(into),
            Self::Select {
                when,
                then,
                otherwise,
            } => {
                when.categories(into);
                then.categories(into);
                otherwise.categories(into);
            }
        }
    }

    fn check(&self) -> Result<(), String> {
        let finite = |values: &[f32]| -> Result<(), String> {
            match values.iter().find(|value| !value.is_finite()) {
                Some(value) => Err(format!("{value} is not a finite number")),
                None => Ok(()),
            }
        };
        match self {
            Self::Constant(value) => finite(&[*value]),
            Self::Noise {
                frequency, octaves, ..
            } => {
                if !(frequency.is_finite() && *frequency > 0.0) {
                    Err(format!(
                        "noise frequency {frequency} is not a positive number"
                    ))
                } else if !(1..=16).contains(octaves) {
                    Err(format!("noise with {octaves} octaves; 1 to 16 are allowed"))
                } else {
                    Ok(())
                }
            }
            Self::Input(_)
            | Self::X
            | Self::Y
            | Self::Row(..)
            | Self::Parent(_)
            | Self::Index
            | Self::Count
            | Self::Share(_) => Ok(()),
            Self::Random(low, high) => {
                finite(&[*low, *high])?;
                if low > high {
                    return Err(format!(
                        "a random number from {low} to {high}, low above high"
                    ));
                }
                Ok(())
            }
            Self::Is(_, names) if names.is_empty() => Err("a category test of no names".to_owned()),
            Self::Is(..) => Ok(()),
            Self::Distance((x, y)) | Self::Angle((x, y)) => finite(&[*x, *y]),
            Self::Add(a, b)
            | Self::Sub(a, b)
            | Self::Mul(a, b)
            | Self::Min(a, b)
            | Self::Max(a, b) => a.check().and_then(|()| b.check()),
            Self::Abs(a) | Self::Floor(a) | Self::Sin(a) => a.check(),
            Self::Clamp(a, low, high) => {
                finite(&[*low, *high])?;
                if low > high {
                    return Err(format!("clamp between {low} and {high}, low above high"));
                }
                a.check()
            }
            Self::Smoothstep(low, high, a) => {
                finite(&[*low, *high])?;
                if low == high {
                    return Err(format!("smoothstep with both edges at {low}"));
                }
                a.check()
            }
            Self::Remap(a, (from_low, from_high), (to_low, to_high)) => {
                finite(&[*from_low, *from_high, *to_low, *to_high])?;
                if from_low == from_high {
                    return Err(format!("remap from a range of one value, {from_low}"));
                }
                a.check()
            }
            Self::Curve(a, points) => {
                if points.len() < 2 {
                    return Err(format!(
                        "a curve through {} points; it needs two",
                        points.len()
                    ));
                }
                for (x, y) in points {
                    finite(&[*x, *y])?;
                }
                if let Some(pair) = points.windows(2).find(|pair| pair[0].0 >= pair[1].0) {
                    return Err(format!(
                        "curve points at x {} then {}; x has to increase",
                        pair[0].0, pair[1].0
                    ));
                }
                a.check()
            }
            Self::Match {
                cases,
                otherwise,
                blend,
                ..
            } => {
                if *blend > MAX_BLEND {
                    return Err(format!(
                        "a blend of {blend} cells; at most {MAX_BLEND} are allowed"
                    ));
                }
                for (index, (name, case)) in cases.iter().enumerate() {
                    if cases[..index].iter().any(|(earlier, _)| earlier == name) {
                        return Err(format!("two cases for category {name:?}"));
                    }
                    case.check()?;
                }
                otherwise.check()
            }
            Self::Select {
                when,
                then,
                otherwise,
            } => when
                .check()
                .and_then(|()| then.check())
                .and_then(|()| otherwise.check()),
        }
    }
}

/// Why a pack could not be loaded.
#[derive(Clone, Debug, PartialEq, thiserror::Error)]
pub enum PackError {
    #[error("not a pack: {0}")]
    Syntax(String),
    #[error("a pack of version {found}; this Wave Forge reads version {supported}")]
    Version { found: u32, supported: u32 },
    #[error("two stages are named {0:?}")]
    DuplicateName(String),
    #[error("stage {stage:?} reads {input:?}, which no stage is named")]
    UnknownInput { stage: String, input: String },
    #[error("stage {stage:?}: {message}")]
    Invalid { stage: String, message: String },
    #[error("these stages read each other in a cycle: {0:?}")]
    Cycle(Vec<String>),
    #[error("two tables are named {0:?}")]
    DuplicateTable(String),
    #[error("table {table:?}: {message}")]
    InvalidTable { table: String, message: String },
}

/// Where an expression is evaluated, which decides what its leaves may read.
#[derive(Clone, Copy)]
enum Place<'a> {
    /// A stage's column.
    Column,
    /// How many rows a generated table has for one parent row, or in all; with the parent table's
    /// columns if it has one.
    Count { parent: Option<&'a [String]> },
    /// A generated table's row, with the parent table's columns if it has one.
    Row { parent: Option<&'a [String]> },
}

/// Whether every leaf `visit` reaches may be read at `place`, and every table column it names
/// exists; `columns` holds each table's columns by table name.
fn check_place(
    visit: impl FnOnce(&mut dyn FnMut(&Expr)),
    place: Place<'_>,
    columns: &BTreeMap<String, Vec<String>>,
) -> Result<(), String> {
    let mut problem = None;
    visit(&mut |node| {
        if problem.is_none() {
            problem = leaf_allowed(node, place, columns).err();
        }
    });
    problem.map_or(Ok(()), Err)
}

fn leaf_allowed(
    node: &Expr,
    place: Place<'_>,
    columns: &BTreeMap<String, Vec<String>>,
) -> Result<(), String> {
    let in_stage = || {
        Err(format!(
            "a stage reads {node:?}, which only a generated table's expressions read; a stage \
             reads a table through Row"
        ))
    };
    let in_count = || {
        Err(format!(
            "a table's count reads {node:?}, which depends on the count itself"
        ))
    };
    let of_parent = |parent: Option<&[String]>, column: &str| match parent {
        None => Err(format!(
            "it reads the parent's {column:?}, but the table has no parent"
        )),
        Some(names) if names.iter().any(|name| name == column) => Ok(()),
        Some(_) => Err(format!("the parent table has no column {column:?}")),
    };
    match node {
        Expr::Constant(_)
        | Expr::Add(..)
        | Expr::Sub(..)
        | Expr::Mul(..)
        | Expr::Min(..)
        | Expr::Max(..)
        | Expr::Abs(_)
        | Expr::Floor(_)
        | Expr::Sin(_)
        | Expr::Clamp(..)
        | Expr::Smoothstep(..)
        | Expr::Remap(..)
        | Expr::Curve(..)
        | Expr::Select { .. } => Ok(()),
        Expr::Noise { .. }
        | Expr::Input(_)
        | Expr::X
        | Expr::Y
        | Expr::Distance(_)
        | Expr::Angle(_)
        | Expr::Is(..)
        | Expr::Match { .. } => match place {
            Place::Column => Ok(()),
            Place::Count { .. } | Place::Row { .. } => Err(format!(
                "a table's expression reads {node:?}, which is a stage's; a table reads only its \
                 parent and its own hash stream"
            )),
        },
        Expr::Row(table, column) => match place {
            Place::Column => match columns.get(table) {
                None => Err(format!(
                    "it reads a row of {table:?}, which no table is named"
                )),
                Some(names) if names.iter().any(|name| name == column) => Ok(()),
                Some(_) => Err(format!("table {table:?} has no column {column:?}")),
            },
            Place::Count { .. } | Place::Row { .. } => {
                Err("a table's expression reads a focused row, which only stages read".to_owned())
            }
        },
        Expr::Parent(column) => match place {
            Place::Column => in_stage(),
            Place::Count { parent } | Place::Row { parent } => of_parent(parent, column),
        },
        Expr::Random(..) => match place {
            Place::Column => in_stage(),
            Place::Count { .. } | Place::Row { .. } => Ok(()),
        },
        Expr::Index | Expr::Count => match place {
            Place::Column => in_stage(),
            Place::Count { .. } => in_count(),
            Place::Row { .. } => Ok(()),
        },
        Expr::Share(column) => match place {
            Place::Column => in_stage(),
            Place::Count { .. } => in_count(),
            Place::Row { parent } => of_parent(parent, column),
        },
    }
}

/// One table of facts, checked and linked to its parent.
#[derive(Clone, Debug, PartialEq)]
pub(crate) struct Schema {
    pub(crate) name: String,
    pub(crate) kind: TableKind,
    pub(crate) parent: Option<usize>,
    /// Its columns' names, in the order its rows hold their values.
    pub(crate) columns: Vec<String>,
    /// Mixed into its rows' hash streams, so two tables never share one.
    pub(crate) salt: u32,
}

impl Schema {
    /// The index of the column named `name` in the table's rows.
    pub(crate) fn column(&self, name: &str) -> Option<usize> {
        self.columns.iter().position(|column| column == name)
    }
}

/// A pack's tables linked: each table, the index of each by name, and their indices parents first.
type Linked = (Vec<Schema>, BTreeMap<String, usize>, Vec<usize>);

/// The tables of a pack, checked and linked.
fn link_tables(defs: Vec<TableDef>) -> Result<Linked, PackError> {
    let mut by_name = BTreeMap::new();
    for (index, def) in defs.iter().enumerate() {
        if by_name.insert(def.name.clone(), index).is_some() {
            return Err(PackError::DuplicateTable(def.name.clone()));
        }
    }
    let columns: Vec<Vec<String>> = defs
        .iter()
        .map(|def| match &def.kind {
            TableKind::Given { columns } => columns.iter().map(|(name, _)| name.clone()).collect(),
            TableKind::Generated { columns, .. } => {
                columns.iter().map(|(name, _)| name.clone()).collect()
            }
        })
        .collect();
    let by_columns: BTreeMap<String, Vec<String>> = defs
        .iter()
        .zip(&columns)
        .map(|(def, names)| (def.name.clone(), names.clone()))
        .collect();
    let mut tables = Vec::with_capacity(defs.len());
    for (def, names) in defs.into_iter().zip(columns) {
        let invalid = |message: String| PackError::InvalidTable {
            table: def.name.clone(),
            message,
        };
        if let Some((index, name)) = names
            .iter()
            .enumerate()
            .find(|(index, name)| names[..*index].contains(name))
        {
            return Err(invalid(format!(
                "two columns are named {name:?} (column {index})"
            )));
        }
        let parent = match &def.kind {
            TableKind::Given { columns } => {
                for (name, column) in columns {
                    if let Column::Names(list) = column {
                        if list.is_empty() {
                            return Err(invalid(format!("column {name:?} has no names")));
                        }
                        if let Some(twice) = list
                            .iter()
                            .enumerate()
                            .find(|(index, known)| list[..*index].contains(known))
                        {
                            return Err(invalid(format!(
                                "column {name:?} lists {:?} twice",
                                twice.1
                            )));
                        }
                    }
                }
                None
            }
            TableKind::Generated {
                parent,
                count,
                columns,
            } => {
                let (parent, parent_columns) = match parent {
                    None => (None, None),
                    Some(name) => {
                        let index = *by_name
                            .get(name)
                            .ok_or_else(|| invalid(format!("its parent {name:?} is no table")))?;
                        (Some(index), Some(by_columns[name].as_slice()))
                    }
                };
                count
                    .check()
                    .map_err(|message| invalid(format!("count: {message}")))?;
                check_place(
                    |f| count.visit(f),
                    Place::Count {
                        parent: parent_columns,
                    },
                    &by_columns,
                )
                .map_err(|message| invalid(format!("count: {message}")))?;
                for (name, expr) in columns {
                    let in_column =
                        |message: String| invalid(format!("column {name:?}: {message}"));
                    expr.check().map_err(in_column)?;
                    check_place(
                        |f| expr.visit(f),
                        Place::Row {
                            parent: parent_columns,
                        },
                        &by_columns,
                    )
                    .map_err(in_column)?;
                }
                parent
            }
        };
        tables.push(Schema {
            salt: salt(&def.name) ^ 0x7461_626C,
            name: def.name,
            kind: def.kind,
            parent,
            columns: names,
        });
    }
    // A table's depth is how many parents it has above it; a chain longer than the tables are
    // many has come back to itself.
    let mut depths = Vec::with_capacity(tables.len());
    for (index, table) in tables.iter().enumerate() {
        let mut depth = 0;
        let mut at = table.parent;
        while let Some(parent) = at {
            depth += 1;
            if parent == index || depth > tables.len() {
                return Err(PackError::InvalidTable {
                    table: table.name.clone(),
                    message: "its parents lead back to it".to_owned(),
                });
            }
            at = tables[parent].parent;
        }
        depths.push(depth);
    }
    let mut order: Vec<usize> = (0..tables.len()).collect();
    order.sort_by_key(|&index| depths[index]);
    Ok((tables, by_name, order))
}

/// One stage, checked and linked to the stages it reads.
#[derive(Clone, Debug, PartialEq)]
pub(crate) struct Stage {
    pub(crate) name: String,
    pub(crate) kind: StageKind,
    /// The stages it reads, by index, and how far beyond its chunk it reads each.
    pub(crate) inputs: Vec<(usize, Reach)>,
    /// Mixed into every random decision the stage makes, so two stages never share a stream.
    pub(crate) salt: u32,
    /// WFC cells per column along each axis.
    pub(crate) scale: u32,
    /// The tables whose focused row it reads.
    pub(crate) tables: Vec<usize>,
}

/// A pack that loaded: every stage linked to its inputs, in an order where inputs come first.
#[derive(Clone, Debug, PartialEq)]
pub struct Pack {
    pub(crate) stages: Vec<Stage>,
    pub(crate) by_name: BTreeMap<String, usize>,
    /// Stage indices, each after every stage it reads.
    pub(crate) order: Vec<usize>,
    pub(crate) tables: Vec<Schema>,
    pub(crate) table_by_name: BTreeMap<String, usize>,
    /// Table indices, each after its parent.
    pub(crate) table_order: Vec<usize>,
}

impl Pack {
    /// Loads a pack from RON.
    ///
    /// # Errors
    /// [`PackError`] naming what is wrong and in which stage.
    pub fn parse(text: &str) -> Result<Self, PackError> {
        let file: PackFile =
            ron::from_str(text).map_err(|error| PackError::Syntax(error.to_string()))?;
        Self::from_file(file)
    }

    /// Checks and links a pack built in code.
    ///
    /// # Errors
    /// [`PackError`] naming what is wrong and in which stage.
    pub fn from_file(file: PackFile) -> Result<Self, PackError> {
        if file.version != PACK_VERSION {
            return Err(PackError::Version {
                found: file.version,
                supported: PACK_VERSION,
            });
        }
        let (tables, table_by_name, table_order) = link_tables(file.tables)?;
        let columns: BTreeMap<String, Vec<String>> = tables
            .iter()
            .map(|table| (table.name.clone(), table.columns.clone()))
            .collect();
        let mut by_name = BTreeMap::new();
        for (index, stage) in file.stages.iter().enumerate() {
            if by_name.insert(stage.name.clone(), index).is_some() {
                return Err(PackError::DuplicateName(stage.name.clone()));
            }
        }
        let outputs: Vec<Output> = file.stages.iter().map(|def| def.kind.output()).collect();
        let scales: Vec<u32> = file.stages.iter().map(|def| def.scale).collect();
        let categories: Vec<Vec<String>> = file
            .stages
            .iter()
            .map(|def| {
                def.kind
                    .categories()
                    .into_iter()
                    .map(str::to_owned)
                    .collect()
            })
            .collect();
        let mut stages = Vec::with_capacity(file.stages.len());
        // Which table each TableSites stage reads, for the Solve stages that choose by its rows.
        let site_tables: BTreeMap<String, String> = file
            .stages
            .iter()
            .filter_map(|def| match &def.kind {
                StageKind::TableSites { table, .. } => Some((def.name.clone(), table.clone())),
                _ => None,
            })
            .collect();
        for def in file.stages {
            let invalid = |message: String| PackError::Invalid {
                stage: def.name.clone(),
                message,
            };
            if def.scale == 0 {
                return Err(invalid("a scale of 0 cells".to_owned()));
            }
            if def.scale != 1
                && matches!(
                    def.kind,
                    StageKind::Sites { .. }
                        | StageKind::TableSites { .. }
                        | StageKind::TableCurves { .. }
                        | StageKind::Apply { .. }
                        | StageKind::Flatten { .. }
                        | StageKind::Solve { .. }
                        | StageKind::Scatter { .. }
                )
            {
                return Err(invalid(format!(
                    "a scale of {}; sites, flattening, towns and scatter work on the WFC lattice, \
                     scale 1",
                    def.scale
                )));
            }
            let reads: Vec<(&str, Reach, Output)> = match &def.kind {
                StageKind::Field(expr) => {
                    expr.check().map_err(invalid)?;
                    check_place(|f| expr.visit(f), Place::Column, &columns).map_err(invalid)?;
                    let mut tests = Vec::new();
                    expr.categories(&mut tests);
                    check_categories(&categories, &by_name, &tests).map_err(invalid)?;
                    let mut names = Vec::new();
                    expr.inputs(&mut names);
                    widest_reads(names)
                }
                StageKind::Rules { rules, .. } => {
                    let count = def.kind.categories().len();
                    if count > MAX_CATEGORIES {
                        return Err(invalid(format!(
                            "{count} categories; at most {MAX_CATEGORIES} are allowed"
                        )));
                    }
                    let mut names = Vec::new();
                    let mut tests = Vec::new();
                    for rule in rules {
                        for condition in &rule.when {
                            condition.check().map_err(invalid)?;
                            check_place(|f| condition.visit(f), Place::Column, &columns)
                                .map_err(invalid)?;
                            condition.inputs(&mut names);
                            condition.categories(&mut tests);
                        }
                    }
                    check_categories(&categories, &by_name, &tests).map_err(invalid)?;
                    widest_reads(names)
                }
                StageKind::Blur { input, radius } | StageKind::Delta { input, radius } => {
                    vec![(input.as_str(), Reach::Cells(*radius), Output::Field)]
                }
                StageKind::Area { input, distance } => {
                    if *distance == 0 {
                        return Err(invalid("an area measured 0 cells out".to_owned()));
                    }
                    vec![(input.as_str(), Reach::Cells(*distance), Output::Categories)]
                }
                StageKind::Sites {
                    height,
                    region,
                    size,
                    chance,
                } => {
                    if !(1 <= size.0 && size.0 <= size.1) {
                        return Err(invalid(format!(
                            "site sizes {} to {} chunks are not a range from 1",
                            size.0, size.1
                        )));
                    }
                    if *region < size.1 + 2 {
                        return Err(invalid(format!(
                            "a region of {region} chunks cannot keep a site of {} chunks one \
                             chunk inside it",
                            size.1
                        )));
                    }
                    if !(0.0..=1.0).contains(chance) {
                        return Err(invalid(format!("chance {chance} is not between 0 and 1")));
                    }
                    // A chunk's site lies within the chunk's region, so its footprint is at most
                    // a region away.
                    vec![(height.as_str(), Reach::Chunks(*region), Output::Field)]
                }
                StageKind::TableSites {
                    table,
                    height,
                    at,
                    size,
                    max_size,
                } => {
                    if *max_size == 0 {
                        return Err(invalid("sites of at most 0 chunks".to_owned()));
                    }
                    let names = columns.get(table).ok_or_else(|| {
                        invalid(format!("it reads {table:?}, which no table is named"))
                    })?;
                    for column in [&at.0, &at.1, size] {
                        if !names.contains(column) {
                            return Err(invalid(format!(
                                "table {table:?} has no column {column:?}"
                            )));
                        }
                    }
                    // A site overlapping the chunk reaches at most `max_size` chunks from it.
                    vec![(height.as_str(), Reach::Chunks(*max_size), Output::Field)]
                }
                StageKind::TableCurves {
                    table,
                    from,
                    to,
                    radius,
                } => {
                    let names = columns.get(table).ok_or_else(|| {
                        invalid(format!("it reads {table:?}, which no table is named"))
                    })?;
                    for column in [&from.0, &from.1, &to.0, &to.1, radius] {
                        if !names.contains(column) {
                            return Err(invalid(format!(
                                "table {table:?} has no column {column:?}"
                            )));
                        }
                    }
                    Vec::new()
                }
                StageKind::Apply {
                    height,
                    curves,
                    max_radius,
                    blend,
                    profile,
                } => {
                    if let Profile::Carve(depth) = profile
                        && !depth.is_finite()
                    {
                        return Err(invalid(format!("a carve {depth} deep")));
                    }
                    // A column is changed by any curve within its radius and blend, and reads the
                    // height at the nearest point of the curve's centre line.
                    let reach = Reach::Cells(max_radius + blend);
                    vec![
                        (height.as_str(), reach, Output::Field),
                        (curves.as_str(), reach, Output::Curves),
                    ]
                }
                StageKind::Flatten {
                    height,
                    sites,
                    blend,
                } => vec![
                    (height.as_str(), Reach::Cells(0), Output::Field),
                    (sites.as_str(), Reach::Cells(*blend), Output::Sites),
                ],
                StageKind::Region {
                    region,
                    halo,
                    inputs,
                    budget,
                    ..
                } => {
                    if *region == 0 {
                        return Err(invalid("a region of 0 chunks".to_owned()));
                    }
                    if !(1..=MAX_BUDGET).contains(budget) {
                        return Err(invalid(format!(
                            "a budget of {budget} attempts; 1 to {MAX_BUDGET} are allowed"
                        )));
                    }
                    // A chunk may lie anywhere in its region, so the job's view of its inputs,
                    // the region and its halo, reaches that far from any chunk of it.
                    let reach = Reach::Chunks(region - 1 + halo);
                    inputs
                        .iter()
                        .map(|name| (name.as_str(), reach, Output::Field))
                        .collect()
                }
                StageKind::Solve { sites, .. } => {
                    vec![(sites.as_str(), Reach::Cells(0), Output::Sites)]
                }
                StageKind::Scatter {
                    height,
                    spacing,
                    chance,
                    between,
                    max_slope,
                    avoid,
                    apart,
                    ..
                } => {
                    if *spacing == 0 {
                        return Err(invalid("a spacing of 0 cells".to_owned()));
                    }
                    if !(0.0..=1.0).contains(chance) {
                        return Err(invalid(format!("chance {chance} is not between 0 and 1")));
                    }
                    if between
                        .is_some_and(|(low, high)| low.is_nan() || high.is_nan() || low > high)
                    {
                        return Err(invalid(format!("the height range {between:?} is empty")));
                    }
                    if max_slope.is_some_and(|slope| slope.is_nan() || slope < 0.0) {
                        return Err(invalid(format!("a slope limit of {max_slope:?}")));
                    }
                    // Candidates within `apart` are judged by their own tests, which read the
                    // height one cell around them for the slope.
                    let slope = u32::from(max_slope.is_some());
                    let mut reads =
                        vec![(height.as_str(), Reach::Cells(apart + slope), Output::Field)];
                    if let Some((sites, margin)) = avoid {
                        reads.push((sites.as_str(), Reach::Cells(apart + margin), Output::Sites));
                    }
                    reads
                }
            };
            let mut inputs = Vec::with_capacity(reads.len());
            for (name, reach, expected) in reads {
                let index = *by_name.get(name).ok_or_else(|| PackError::UnknownInput {
                    stage: def.name.clone(),
                    input: name.to_owned(),
                })?;
                if scales[index] < def.scale || !scales[index].is_multiple_of(def.scale) {
                    return Err(invalid(format!(
                        "it reads {name:?}, of scale {}, from scale {}; a stage reads only stages \
                         as coarse as itself or coarser, by a whole factor",
                        scales[index], def.scale
                    )));
                }
                if outputs[index] != expected {
                    return Err(invalid(format!(
                        "it reads {name:?} as {expected:?}, but that stage produces {:?}",
                        outputs[index]
                    )));
                }
                inputs.push((index, reach));
            }
            if let StageKind::Solve {
                sites,
                by: Some((column, cases)),
                ..
            } = &def.kind
            {
                check_solve_by(&site_tables, &tables, &table_by_name, sites, column, cases)
                    .map_err(invalid)?;
            }
            let mut read_tables: Vec<usize> = Vec::new();
            let mut note = |node: &Expr| {
                if let Expr::Row(table, _) = node {
                    let index = table_by_name[table];
                    if !read_tables.contains(&index) {
                        read_tables.push(index);
                    }
                }
            };
            match &def.kind {
                StageKind::Field(expr) => expr.visit(&mut note),
                StageKind::Rules { rules, .. } => {
                    for condition in rules.iter().flat_map(|rule| &rule.when) {
                        condition.visit(&mut note);
                    }
                }
                StageKind::TableSites { table, .. } | StageKind::TableCurves { table, .. } => {
                    read_tables.push(table_by_name[table]);
                }
                StageKind::Blur { .. }
                | StageKind::Delta { .. }
                | StageKind::Area { .. }
                | StageKind::Sites { .. }
                | StageKind::Apply { .. }
                | StageKind::Flatten { .. }
                | StageKind::Solve { .. }
                | StageKind::Region { .. }
                | StageKind::Scatter { .. } => {}
            }
            stages.push(Stage {
                tables: read_tables,
                salt: salt(&def.name),
                scale: def.scale,
                name: def.name,
                kind: def.kind,
                inputs,
            });
        }
        let mut point_ids: BTreeMap<u16, &str> = BTreeMap::new();
        for stage in &stages {
            if let StageKind::Scatter { .. } = stage.kind
                && let Some(other) = point_ids.insert(point_stage_id(stage.salt), &stage.name)
            {
                return Err(PackError::Invalid {
                    stage: stage.name.clone(),
                    message: format!(
                        "its points' ids would share a stage number with {other:?}; rename one"
                    ),
                });
            }
        }
        let order = topological_order(&stages)?;
        Ok(Self {
            stages,
            by_name,
            order,
            tables,
            table_by_name,
            table_order,
        })
    }

    /// What the stage named `name` does, if there is one.
    #[must_use]
    pub fn kind(&self, name: &str) -> Option<&StageKind> {
        self.index(name).map(|index| &self.stages[index].kind)
    }

    /// The stages' names, in the order the file lists them.
    pub fn stage_names(&self) -> impl Iterator<Item = &str> {
        self.stages.iter().map(|stage| stage.name.as_str())
    }

    /// Where the table named `name` takes its rows from and what its columns hold, if there is
    /// one.
    #[must_use]
    pub fn table(&self, name: &str) -> Option<&TableKind> {
        let index = *self.table_by_name.get(name)?;
        Some(&self.tables[index].kind)
    }

    /// How far beyond a column of `target` each stage it depends on has to be generated, in WFC
    /// cells along the lattice's x, for chunks of `size` columns: the largest sum of reaches along
    /// any path from `target` to it, each in its reader's columns times the reader's scale, and one
    /// column more of an input coarser than its reader, which is read between its columns.
    /// `target` itself is included, at 0. `None` if no stage is named `target`.
    #[must_use]
    pub fn reach(&self, target: &str, size: [u32; 2]) -> Option<BTreeMap<String, u32>> {
        let target = *self.by_name.get(target)?;
        let mut reach: BTreeMap<usize, u32> = BTreeMap::from([(target, 0)]);
        // Consumers come after their inputs in `order`, so walking it backwards visits every
        // consumer of a stage before the stage itself.
        for &index in self.order.iter().rev() {
            let Some(&here) = reach.get(&index) else {
                continue;
            };
            let scale = self.stages[index].scale;
            for &(input, span) in &self.stages[index].inputs {
                let coarser = self.stages[input].scale;
                // A coarser input is read between its columns, so one more of them either side.
                let between = if coarser > scale { coarser } else { 0 };
                let there = reach.entry(input).or_insert(0);
                *there = (*there).max(here + span.cells(size)[0] * scale + between);
            }
        }
        Some(
            reach
                .into_iter()
                .map(|(index, cells)| (self.stages[index].name.clone(), cells))
                .collect(),
        )
    }

    /// The scale `stage` works at, in WFC cells per column.
    #[must_use]
    pub fn scale(&self, stage: &str) -> Option<u32> {
        Some(self.stages[*self.by_name.get(stage)?].scale)
    }

    pub(crate) fn index(&self, name: &str) -> Option<usize> {
        self.by_name.get(name).copied()
    }
}

/// The stage number a Scatter stage's points carry in their ids: 15 bits of its salt, never 0,
/// which is the tiles'.
pub(crate) const fn point_stage_id(salt: u32) -> u16 {
    (salt % 0x7FFF) as u16 + 1
}

/// Each stage an expression reads, once for each kind it reads it as, at the widest reach any part
/// of it reads that stage at: the runtime gives a stage one view of each input. A stage read as two
/// kinds stays two reads, so the check of what each stage produces refuses the wrong one.
fn widest_reads(reads: Vec<(&str, Output, u32)>) -> Vec<(&str, Reach, Output)> {
    let mut widest: Vec<(&str, Reach, Output)> = Vec::new();
    for (name, output, reach) in reads {
        match widest
            .iter_mut()
            .find(|(known, _, kind)| *known == name && *kind == output)
        {
            Some((_, Reach::Cells(cells), _)) => *cells = (*cells).max(reach),
            Some(_) => unreachable!("an expression reads in cells"),
            None => widest.push((name, Reach::Cells(reach), output)),
        }
    }
    widest
}

/// Whether every category test names categories its Rules stage has. A test of a stage that is not
/// a Rules stage, or of no stage, is left to the check of what each stage reads.
fn check_categories(
    categories: &[Vec<String>],
    by_name: &BTreeMap<String, usize>,
    tests: &[(&str, Vec<&str>)],
) -> Result<(), String> {
    for (input, names) in tests {
        let Some(&index) = by_name.get(*input) else {
            continue;
        };
        let known = &categories[index];
        if known.is_empty() {
            continue;
        }
        if let Some(missing) = names
            .iter()
            .find(|name| !known.iter().any(|known| known == *name))
        {
            return Err(format!("{input:?} has no category {missing:?}"));
        }
    }
    Ok(())
}

/// Whether a Solve stage over `sites` may choose its rule set by `column`: the sites come from a
/// given table whose `column` holds names, and `cases` name each of them at most once.
fn check_solve_by(
    site_tables: &BTreeMap<String, String>,
    tables: &[Schema],
    table_by_name: &BTreeMap<String, usize>,
    sites: &str,
    column: &str,
    cases: &[(String, String)],
) -> Result<(), String> {
    let table = site_tables.get(sites).ok_or_else(|| {
        format!("it chooses its rule set by a column, but {sites:?} is no TableSites stage")
    })?;
    let TableKind::Given { columns } = &tables[table_by_name[table]].kind else {
        return Err(format!(
            "it chooses its rule set by a column of {table:?}, which is a generated table; only a \
             given table has names"
        ));
    };
    let Some((_, Column::Names(names))) = columns.iter().find(|(name, _)| name == column) else {
        return Err(format!("table {table:?} has no column of names {column:?}"));
    };
    for (index, (name, _)) in cases.iter().enumerate() {
        if !names.contains(name) {
            return Err(format!("{column:?} has no name {name:?}"));
        }
        if cases[..index].iter().any(|(earlier, _)| earlier == name) {
            return Err(format!("two rule sets for {name:?}"));
        }
    }
    Ok(())
}

/// FNV-1a of a stage's name: the same for a stage wherever it sits in the pack, so adding or
/// reordering stages changes no other stage's random decisions.
pub(crate) fn salt(name: &str) -> u32 {
    name.bytes().fold(0x811C_9DC5_u32, |hash, byte| {
        (hash ^ u32::from(byte)).wrapping_mul(0x0100_0193)
    })
}

/// Stage indices with every stage after the ones it reads, or the stages of a cycle.
fn topological_order(stages: &[Stage]) -> Result<Vec<usize>, PackError> {
    #[derive(Clone, Copy, PartialEq)]
    enum Mark {
        New,
        Visiting,
        Done,
    }
    fn visit(
        index: usize,
        stages: &[Stage],
        marks: &mut [Mark],
        path: &mut Vec<usize>,
        order: &mut Vec<usize>,
    ) -> Result<(), PackError> {
        match marks[index] {
            Mark::Done => return Ok(()),
            Mark::Visiting => {
                let start = path
                    .iter()
                    .position(|&i| i == index)
                    .expect("a stage being visited is on the path");
                return Err(PackError::Cycle(
                    path[start..]
                        .iter()
                        .map(|&i| stages[i].name.clone())
                        .collect(),
                ));
            }
            Mark::New => {}
        }
        marks[index] = Mark::Visiting;
        path.push(index);
        for &(input, _) in &stages[index].inputs {
            visit(input, stages, marks, path, order)?;
        }
        path.pop();
        marks[index] = Mark::Done;
        order.push(index);
        Ok(())
    }
    let mut marks = vec![Mark::New; stages.len()];
    let mut order = Vec::with_capacity(stages.len());
    for index in 0..stages.len() {
        visit(index, stages, &mut marks, &mut Vec::new(), &mut order)?;
    }
    Ok(order)
}

#[cfg(test)]
mod tests {
    use super::*;

    const TERRAIN: &str = r#"(
        version: 1,
        stages: [
            (name: "rough", kind: Field(Noise(frequency: 0.1, octaves: 3))),
            (name: "smooth", kind: Blur(input: "rough", radius: 2)),
            (name: "height", kind: Field(Mul(Input("smooth"), Constant(8.0)))),
            (name: "softer", kind: Blur(input: "height", radius: 3)),
        ],
    )"#;

    fn pack_with(stages: &str) -> Result<Pack, PackError> {
        Pack::parse(&format!("(version: 1, stages: [{stages}])"))
    }

    #[test]
    fn a_pack_orders_each_stage_after_what_it_reads() {
        let pack = Pack::parse(TERRAIN).expect("a valid pack");

        let position = |name: &str| {
            let index = pack.index(name).expect("a stage");
            pack.order
                .iter()
                .position(|&i| i == index)
                .expect("ordered")
        };

        assert!(position("rough") < position("smooth"));
        assert!(position("smooth") < position("height"));
        assert!(position("height") < position("softer"));
    }

    #[test]
    fn reach_adds_up_along_the_longest_path() {
        let pack = Pack::parse(TERRAIN).expect("a valid pack");

        let reach = pack.reach("softer", [8, 8]).expect("a stage");

        assert_eq!(
            reach,
            BTreeMap::from([
                ("softer".to_owned(), 0),
                ("height".to_owned(), 3),
                ("smooth".to_owned(), 3),
                ("rough".to_owned(), 5),
            ])
        );
    }

    #[test]
    fn a_stage_that_reads_a_missing_one_is_named() {
        let result = pack_with(r#"(name: "a", kind: Blur(input: "nowhere", radius: 1))"#);

        assert_eq!(
            result,
            Err(PackError::UnknownInput {
                stage: "a".to_owned(),
                input: "nowhere".to_owned()
            })
        );
    }

    #[test]
    fn stages_that_read_each_other_are_a_cycle() {
        let result = pack_with(
            r#"(name: "a", kind: Blur(input: "b", radius: 1)),
               (name: "b", kind: Field(Input("a")))"#,
        );

        let Err(PackError::Cycle(stages)) = result else {
            panic!("expected a cycle, got {result:?}");
        };
        let mut stages = stages;
        stages.sort();
        assert_eq!(stages, vec!["a".to_owned(), "b".to_owned()]);
    }

    #[test]
    fn two_stages_of_one_name_are_refused() {
        let result = pack_with(
            r#"(name: "a", kind: Field(Constant(1.0))), (name: "a", kind: Field(Constant(2.0)))"#,
        );

        assert_eq!(result, Err(PackError::DuplicateName("a".to_owned())));
    }

    #[test]
    fn a_stage_reading_sites_as_a_field_is_named() {
        let result = pack_with(
            r#"(name: "h", kind: Field(Constant(1.0))),
               (name: "towns", kind: Sites(height: "h", region: 6, size: (1, 3), chance: 0.5)),
               (name: "wrong", kind: Blur(input: "towns", radius: 1))"#,
        );

        assert!(
            matches!(&result, Err(PackError::Invalid { stage, .. }) if stage == "wrong"),
            "{result:?}"
        );
    }

    #[test]
    fn a_region_too_small_for_its_sites_is_refused() {
        let result = pack_with(
            r#"(name: "h", kind: Field(Constant(1.0))),
               (name: "towns", kind: Sites(height: "h", region: 4, size: (1, 3), chance: 0.5))"#,
        );

        assert!(
            matches!(&result, Err(PackError::Invalid { stage, .. }) if stage == "towns"),
            "{result:?}"
        );
    }

    #[test]
    fn a_reach_in_chunks_counts_the_chunk_size() {
        let pack = pack_with(
            r#"(name: "h", kind: Field(Constant(1.0))),
               (name: "towns", kind: Sites(height: "h", region: 6, size: (1, 3), chance: 0.5)),
               (name: "level", kind: Flatten(height: "h", sites: "towns", blend: 4))"#,
        )
        .expect("valid");

        let reach = pack.reach("level", [8, 8]).expect("a stage");

        assert_eq!(reach["towns"], 4);
        assert_eq!(reach["h"], 4 + 6 * 8);
    }

    #[test]
    fn two_scatter_stages_whose_point_ids_would_collide_are_refused() {
        let names: Vec<String> = (0..2000).map(|i| format!("s{i}")).collect();
        let mut seen: BTreeMap<u16, &str> = BTreeMap::new();
        let (first, second) = names
            .iter()
            .find_map(|name| {
                seen.insert(point_stage_id(salt(name)), name)
                    .map(|other| (other.to_owned(), name.clone()))
            })
            .expect("15 bits collide within 2000 names");
        let scatter = |name: &str| {
            format!(r#"(name: "{name}", kind: Scatter(kind: "tree", height: "h", spacing: 4))"#)
        };

        let result = pack_with(&format!(
            r#"(name: "h", kind: Field(Constant(1.0))), {}, {}"#,
            scatter(&first),
            scatter(&second)
        ));

        assert!(
            matches!(&result, Err(PackError::Invalid { stage, .. }) if *stage == second),
            "{result:?}"
        );
    }

    #[test]
    fn another_version_is_refused() {
        let result = Pack::parse("(version: 7, stages: [])");

        assert_eq!(
            result,
            Err(PackError::Version {
                found: 7,
                supported: PACK_VERSION
            })
        );
    }

    #[test]
    fn noise_without_octaves_is_named_with_its_stage() {
        let result = pack_with(r#"(name: "n", kind: Field(Noise(frequency: 0.1, octaves: 0)))"#);

        assert!(
            matches!(&result, Err(PackError::Invalid { stage, .. }) if stage == "n"),
            "{result:?}"
        );
    }

    #[test]
    fn an_unknown_field_is_a_syntax_error() {
        let result = Pack::parse("(version: 1, stages: [], extra: 1)");

        assert!(matches!(result, Err(PackError::Syntax(_))), "{result:?}");
    }

    #[test]
    fn a_stage_keeps_its_salt_wherever_it_sits() {
        let first = pack_with(r#"(name: "a", kind: Field(Constant(1.0)))"#).expect("valid");
        let second = pack_with(
            r#"(name: "b", kind: Field(Constant(2.0))), (name: "a", kind: Field(Constant(1.0)))"#,
        )
        .expect("valid");

        let salt_of = |pack: &Pack| pack.stages[pack.index("a").expect("a")].salt;

        assert_eq!(salt_of(&first), salt_of(&second));
    }
}
