//! A pack: the stages a world is generated by, as a file names them.
//!
//! A pack is RON: a version and a list of named stages. A stage reads other stages by name, and how
//! far it reads follows from its parameters (a blur's radius), so a pack never states a reach by
//! hand. Loading checks everything that can be checked before generating: the version, unknown
//! and duplicate names, parameters out of range, and cycles, each error naming the stage.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

/// The pack format this library reads.
pub const PACK_VERSION: u32 = 1;

/// A pack as written in a file.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct PackFile {
    pub version: u32,
    /// The stages in the order a stack shows them; a stage may read any other, earlier or later.
    pub stages: Vec<StageDef>,
}

/// One stage of a pack.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct StageDef {
    pub name: String,
    pub kind: StageKind,
}

/// What a stage does.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub enum StageKind {
    /// A value per cell column, computed from an expression at that column alone.
    Field(Expr),
    /// Another field averaged over the square of `radius` cells around each column.
    Blur { input: String, radius: u32 },
}

/// A field's value at one cell column.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub enum Expr {
    Constant(f32),
    /// Value noise in 0..1: `octaves` layers, the first with `frequency` lattice points per cell,
    /// each next one at twice the frequency and half the weight.
    Noise {
        frequency: f32,
        octaves: u32,
    },
    /// Another field's value at the same column.
    Input(String),
    Add(Box<Expr>, Box<Expr>),
    Mul(Box<Expr>, Box<Expr>),
}

impl Expr {
    fn inputs<'a>(&'a self, into: &mut Vec<&'a str>) {
        match self {
            Self::Constant(_) | Self::Noise { .. } => {}
            Self::Input(name) => into.push(name),
            Self::Add(a, b) | Self::Mul(a, b) => {
                a.inputs(into);
                b.inputs(into);
            }
        }
    }

    fn check(&self) -> Result<(), String> {
        match self {
            Self::Constant(value) if !value.is_finite() => Err(format!("constant {value}")),
            Self::Noise { frequency, octaves } => {
                if !(frequency.is_finite() && *frequency > 0.0) {
                    Err(format!(
                        "noise frequency {frequency} is not a positive number"
                    ))
                } else if !(1..=16).contains(octaves) {
                    Err(format!("noise with {octaves} octaves; 1 to 16 are allowed"))
                } else {
                    Ok(())
                }
            }
            Self::Add(a, b) | Self::Mul(a, b) => a.check().and_then(|()| b.check()),
            Self::Constant(_) | Self::Input(_) => Ok(()),
        }
    }
}

/// Why a pack could not be loaded.
#[derive(Clone, Debug, PartialEq, thiserror::Error)]
pub enum PackError {
    #[error("not a pack: {0}")]
    Syntax(String),
    #[error("a pack of version {found}; this Wave Forge reads version {supported}")]
    Version { found: u32, supported: u32 },
    #[error("two stages are named {0:?}")]
    DuplicateName(String),
    #[error("stage {stage:?} reads {input:?}, which no stage is named")]
    UnknownInput { stage: String, input: String },
    #[error("stage {stage:?}: {message}")]
    Invalid { stage: String, message: String },
    #[error("these stages read each other in a cycle: {0:?}")]
    Cycle(Vec<String>),
}

/// One stage, checked and linked to the stages it reads.
#[derive(Clone, Debug, PartialEq)]
pub(crate) struct Stage {
    pub(crate) name: String,
    pub(crate) kind: StageKind,
    /// The stages it reads, by index, and how many cells beyond a column it reads each.
    pub(crate) inputs: Vec<(usize, u32)>,
    /// Mixed into every random decision the stage makes, so two stages never share a stream.
    pub(crate) salt: u32,
}

/// A pack that loaded: every stage linked to its inputs, in an order where inputs come first.
#[derive(Clone, Debug, PartialEq)]
pub struct Pack {
    pub(crate) stages: Vec<Stage>,
    pub(crate) by_name: BTreeMap<String, usize>,
    /// Stage indices, each after every stage it reads.
    pub(crate) order: Vec<usize>,
}

impl Pack {
    /// Loads a pack from RON.
    ///
    /// # Errors
    /// [`PackError`] naming what is wrong and in which stage.
    pub fn parse(text: &str) -> Result<Self, PackError> {
        let file: PackFile =
            ron::from_str(text).map_err(|error| PackError::Syntax(error.to_string()))?;
        Self::from_file(file)
    }

    /// Checks and links a pack built in code.
    ///
    /// # Errors
    /// [`PackError`] naming what is wrong and in which stage.
    pub fn from_file(file: PackFile) -> Result<Self, PackError> {
        if file.version != PACK_VERSION {
            return Err(PackError::Version {
                found: file.version,
                supported: PACK_VERSION,
            });
        }
        let mut by_name = BTreeMap::new();
        for (index, stage) in file.stages.iter().enumerate() {
            if by_name.insert(stage.name.clone(), index).is_some() {
                return Err(PackError::DuplicateName(stage.name.clone()));
            }
        }
        let mut stages = Vec::with_capacity(file.stages.len());
        for def in file.stages {
            let reads: Vec<(&str, u32)> = match &def.kind {
                StageKind::Field(expr) => {
                    expr.check().map_err(|message| PackError::Invalid {
                        stage: def.name.clone(),
                        message,
                    })?;
                    let mut names = Vec::new();
                    expr.inputs(&mut names);
                    names.into_iter().map(|name| (name, 0)).collect()
                }
                StageKind::Blur { input, radius } => vec![(input.as_str(), *radius)],
            };
            let mut inputs = Vec::with_capacity(reads.len());
            for (name, reach) in reads {
                let index = *by_name.get(name).ok_or_else(|| PackError::UnknownInput {
                    stage: def.name.clone(),
                    input: name.to_owned(),
                })?;
                inputs.push((index, reach));
            }
            stages.push(Stage {
                salt: salt(&def.name),
                name: def.name,
                kind: def.kind,
                inputs,
            });
        }
        let order = topological_order(&stages)?;
        Ok(Self {
            stages,
            by_name,
            order,
        })
    }

    /// The stages' names, in the order the file lists them.
    pub fn stage_names(&self) -> impl Iterator<Item = &str> {
        self.stages.iter().map(|stage| stage.name.as_str())
    }

    /// How far beyond a column of `target` each stage it depends on has to be generated, in cells:
    /// the largest sum of reaches along any path from `target` to it. `target` itself is included,
    /// at 0. `None` if no stage is named `target`.
    #[must_use]
    pub fn reach(&self, target: &str) -> Option<BTreeMap<String, u32>> {
        let target = *self.by_name.get(target)?;
        let mut reach: BTreeMap<usize, u32> = BTreeMap::from([(target, 0)]);
        // Consumers come after their inputs in `order`, so walking it backwards visits every
        // consumer of a stage before the stage itself.
        for &index in self.order.iter().rev() {
            let Some(&here) = reach.get(&index) else {
                continue;
            };
            for &(input, cells) in &self.stages[index].inputs {
                let there = reach.entry(input).or_insert(0);
                *there = (*there).max(here + cells);
            }
        }
        Some(
            reach
                .into_iter()
                .map(|(index, cells)| (self.stages[index].name.clone(), cells))
                .collect(),
        )
    }

    pub(crate) fn index(&self, name: &str) -> Option<usize> {
        self.by_name.get(name).copied()
    }
}

/// FNV-1a of a stage's name: the same for a stage wherever it sits in the pack, so adding or
/// reordering stages changes no other stage's random decisions.
fn salt(name: &str) -> u32 {
    name.bytes().fold(0x811C_9DC5_u32, |hash, byte| {
        (hash ^ u32::from(byte)).wrapping_mul(0x0100_0193)
    })
}

/// Stage indices with every stage after the ones it reads, or the stages of a cycle.
fn topological_order(stages: &[Stage]) -> Result<Vec<usize>, PackError> {
    #[derive(Clone, Copy, PartialEq)]
    enum Mark {
        New,
        Visiting,
        Done,
    }
    fn visit(
        index: usize,
        stages: &[Stage],
        marks: &mut [Mark],
        path: &mut Vec<usize>,
        order: &mut Vec<usize>,
    ) -> Result<(), PackError> {
        match marks[index] {
            Mark::Done => return Ok(()),
            Mark::Visiting => {
                let start = path
                    .iter()
                    .position(|&i| i == index)
                    .expect("a stage being visited is on the path");
                return Err(PackError::Cycle(
                    path[start..]
                        .iter()
                        .map(|&i| stages[i].name.clone())
                        .collect(),
                ));
            }
            Mark::New => {}
        }
        marks[index] = Mark::Visiting;
        path.push(index);
        for &(input, _) in &stages[index].inputs {
            visit(input, stages, marks, path, order)?;
        }
        path.pop();
        marks[index] = Mark::Done;
        order.push(index);
        Ok(())
    }
    let mut marks = vec![Mark::New; stages.len()];
    let mut order = Vec::with_capacity(stages.len());
    for index in 0..stages.len() {
        visit(index, stages, &mut marks, &mut Vec::new(), &mut order)?;
    }
    Ok(order)
}

#[cfg(test)]
mod tests {
    use super::*;

    const TERRAIN: &str = r#"(
        version: 1,
        stages: [
            (name: "rough", kind: Field(Noise(frequency: 0.1, octaves: 3))),
            (name: "smooth", kind: Blur(input: "rough", radius: 2)),
            (name: "height", kind: Field(Mul(Input("smooth"), Constant(8.0)))),
            (name: "softer", kind: Blur(input: "height", radius: 3)),
        ],
    )"#;

    fn pack_with(stages: &str) -> Result<Pack, PackError> {
        Pack::parse(&format!("(version: 1, stages: [{stages}])"))
    }

    #[test]
    fn a_pack_orders_each_stage_after_what_it_reads() {
        let pack = Pack::parse(TERRAIN).expect("a valid pack");

        let position = |name: &str| {
            let index = pack.index(name).expect("a stage");
            pack.order
                .iter()
                .position(|&i| i == index)
                .expect("ordered")
        };

        assert!(position("rough") < position("smooth"));
        assert!(position("smooth") < position("height"));
        assert!(position("height") < position("softer"));
    }

    #[test]
    fn reach_adds_up_along_the_longest_path() {
        let pack = Pack::parse(TERRAIN).expect("a valid pack");

        let reach = pack.reach("softer").expect("a stage");

        assert_eq!(
            reach,
            BTreeMap::from([
                ("softer".to_owned(), 0),
                ("height".to_owned(), 3),
                ("smooth".to_owned(), 3),
                ("rough".to_owned(), 5),
            ])
        );
    }

    #[test]
    fn a_stage_that_reads_a_missing_one_is_named() {
        let result = pack_with(r#"(name: "a", kind: Blur(input: "nowhere", radius: 1))"#);

        assert_eq!(
            result,
            Err(PackError::UnknownInput {
                stage: "a".to_owned(),
                input: "nowhere".to_owned()
            })
        );
    }

    #[test]
    fn stages_that_read_each_other_are_a_cycle() {
        let result = pack_with(
            r#"(name: "a", kind: Blur(input: "b", radius: 1)),
               (name: "b", kind: Field(Input("a")))"#,
        );

        let Err(PackError::Cycle(stages)) = result else {
            panic!("expected a cycle, got {result:?}");
        };
        let mut stages = stages;
        stages.sort();
        assert_eq!(stages, vec!["a".to_owned(), "b".to_owned()]);
    }

    #[test]
    fn two_stages_of_one_name_are_refused() {
        let result = pack_with(
            r#"(name: "a", kind: Field(Constant(1.0))), (name: "a", kind: Field(Constant(2.0)))"#,
        );

        assert_eq!(result, Err(PackError::DuplicateName("a".to_owned())));
    }

    #[test]
    fn another_version_is_refused() {
        let result = Pack::parse("(version: 7, stages: [])");

        assert_eq!(
            result,
            Err(PackError::Version {
                found: 7,
                supported: PACK_VERSION
            })
        );
    }

    #[test]
    fn noise_without_octaves_is_named_with_its_stage() {
        let result = pack_with(r#"(name: "n", kind: Field(Noise(frequency: 0.1, octaves: 0)))"#);

        assert!(
            matches!(&result, Err(PackError::Invalid { stage, .. }) if stage == "n"),
            "{result:?}"
        );
    }

    #[test]
    fn an_unknown_field_is_a_syntax_error() {
        let result = Pack::parse("(version: 1, stages: [], extra: 1)");

        assert!(matches!(result, Err(PackError::Syntax(_))), "{result:?}");
    }

    #[test]
    fn a_stage_keeps_its_salt_wherever_it_sits() {
        let first = pack_with(r#"(name: "a", kind: Field(Constant(1.0)))"#).expect("valid");
        let second = pack_with(
            r#"(name: "b", kind: Field(Constant(2.0))), (name: "a", kind: Field(Constant(1.0)))"#,
        )
        .expect("valid");

        let salt_of = |pack: &Pack| pack.stages[pack.index("a").expect("a")].salt;

        assert_eq!(salt_of(&first), salt_of(&second));
    }
}
