//! A pack: the stages a world is generated by, as a file names them.
//!
//! A pack is RON: a version and a list of named stages. A stage reads other stages by name, and how
//! far it reads follows from its parameters (a blur's radius), so a pack never states a reach by
//! hand. Loading checks everything that can be checked before generating: the version, unknown
//! and duplicate names, parameters out of range, and cycles, each error naming the stage.

use crate::towns::Selector;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

/// The pack format this library reads.
pub const PACK_VERSION: u32 = 1;

/// A pack as written in a file.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct PackFile {
    pub version: u32,
    /// The stages in the order a stack shows them; a stage may read any other, earlier or later.
    pub stages: Vec<StageDef>,
}

/// One stage of a pack.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct StageDef {
    pub name: String,
    pub kind: StageKind,
}

/// What a stage does.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub enum StageKind {
    /// A value per cell column, computed from an expression at that column alone.
    Field(Expr),
    /// Another field averaged over the square of `radius` cells around each column.
    Blur { input: String, radius: u32 },
    /// Settlement sites: rectangles of whole chunks, at most one per square region of `region`
    /// chunks, placed with `chance`, between `size.0` and `size.1` chunks on a side, and kept at
    /// least one chunk inside their region, so two sites are always two chunks apart. Each site's
    /// height is the mean of the `height` field over its footprint's centre and inner corners.
    Sites {
        height: String,
        region: u32,
        size: (u32, u32),
        chance: f32,
    },
    /// The `height` field levelled to each of `sites`' heights inside its footprint and blended
    /// back to the field over `blend` cells around it.
    Flatten {
        height: String,
        sites: String,
        blend: u32,
    },
    /// A town on each of `sites`: a bounded WFC world of the rule set named `rules`, the size of
    /// the site's footprint, solved whole, with `bottom` on its lowest layer and `top` on its
    /// highest.
    Solve {
        sites: String,
        rules: String,
        #[serde(default)]
        bottom: Option<Selector>,
        #[serde(default)]
        top: Option<Selector>,
    },
    /// Points of `kind` standing on the `height` field: one candidate per square block of
    /// `spacing` cells at a hashed column inside it, kept with probability `chance`, if the height
    /// there is within `between`, the slope at most `max_slope` (height per cell), the column at
    /// least `margin` cells from every site of `avoid`, and no kept candidate of higher priority is
    /// closer than `apart` cells. That last test reads neighbours' candidates, never their
    /// results, so points keep their distance across chunk seams.
    Scatter {
        kind: String,
        height: String,
        spacing: u32,
        #[serde(default = "always")]
        chance: f32,
        #[serde(default)]
        between: Option<(f32, f32)>,
        #[serde(default)]
        max_slope: Option<f32>,
        #[serde(default)]
        avoid: Option<(String, u32)>,
        #[serde(default)]
        apart: u32,
    },
}

const fn always() -> f32 {
    1.0
}

/// What a stage produces, which decides which stages may read it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Output {
    Field,
    Sites,
    Tiles,
    Points,
}

impl StageKind {
    pub(crate) const fn output(&self) -> Output {
        match self {
            Self::Field(_) | Self::Blur { .. } | Self::Flatten { .. } => Output::Field,
            Self::Sites { .. } => Output::Sites,
            Self::Solve { .. } => Output::Tiles,
            Self::Scatter { .. } => Output::Points,
        }
    }
}

/// How far beyond its chunk a stage reads an input: in cells, or in whole chunks, which the
/// runtime turns into cells once it knows how large a chunk is.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Reach {
    Cells(u32),
    Chunks(u32),
}

impl Reach {
    /// The reach in cells along each lattice axis, for chunks of `size` cells.
    pub(crate) const fn cells(self, size: [u32; 2]) -> [u32; 2] {
        match self {
            Self::Cells(cells) => [cells, cells],
            Self::Chunks(chunks) => [chunks * size[0], chunks * size[1]],
        }
    }
}

/// A field's value at one cell column.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub enum Expr {
    Constant(f32),
    /// Value noise in 0..1: `octaves` layers, the first with `frequency` lattice points per cell,
    /// each next one at twice the frequency and half the weight.
    Noise {
        frequency: f32,
        octaves: u32,
    },
    /// Another field's value at the same column.
    Input(String),
    Add(Box<Expr>, Box<Expr>),
    Mul(Box<Expr>, Box<Expr>),
}

impl Expr {
    fn inputs<'a>(&'a self, into: &mut Vec<&'a str>) {
        match self {
            Self::Constant(_) | Self::Noise { .. } => {}
            Self::Input(name) => into.push(name),
            Self::Add(a, b) | Self::Mul(a, b) => {
                a.inputs(into);
                b.inputs(into);
            }
        }
    }

    fn check(&self) -> Result<(), String> {
        match self {
            Self::Constant(value) if !value.is_finite() => Err(format!("constant {value}")),
            Self::Noise { frequency, octaves } => {
                if !(frequency.is_finite() && *frequency > 0.0) {
                    Err(format!(
                        "noise frequency {frequency} is not a positive number"
                    ))
                } else if !(1..=16).contains(octaves) {
                    Err(format!("noise with {octaves} octaves; 1 to 16 are allowed"))
                } else {
                    Ok(())
                }
            }
            Self::Add(a, b) | Self::Mul(a, b) => a.check().and_then(|()| b.check()),
            Self::Constant(_) | Self::Input(_) => Ok(()),
        }
    }
}

/// Why a pack could not be loaded.
#[derive(Clone, Debug, PartialEq, thiserror::Error)]
pub enum PackError {
    #[error("not a pack: {0}")]
    Syntax(String),
    #[error("a pack of version {found}; this Wave Forge reads version {supported}")]
    Version { found: u32, supported: u32 },
    #[error("two stages are named {0:?}")]
    DuplicateName(String),
    #[error("stage {stage:?} reads {input:?}, which no stage is named")]
    UnknownInput { stage: String, input: String },
    #[error("stage {stage:?}: {message}")]
    Invalid { stage: String, message: String },
    #[error("these stages read each other in a cycle: {0:?}")]
    Cycle(Vec<String>),
}

/// One stage, checked and linked to the stages it reads.
#[derive(Clone, Debug, PartialEq)]
pub(crate) struct Stage {
    pub(crate) name: String,
    pub(crate) kind: StageKind,
    /// The stages it reads, by index, and how far beyond its chunk it reads each.
    pub(crate) inputs: Vec<(usize, Reach)>,
    /// Mixed into every random decision the stage makes, so two stages never share a stream.
    pub(crate) salt: u32,
}

/// A pack that loaded: every stage linked to its inputs, in an order where inputs come first.
#[derive(Clone, Debug, PartialEq)]
pub struct Pack {
    pub(crate) stages: Vec<Stage>,
    pub(crate) by_name: BTreeMap<String, usize>,
    /// Stage indices, each after every stage it reads.
    pub(crate) order: Vec<usize>,
}

impl Pack {
    /// Loads a pack from RON.
    ///
    /// # Errors
    /// [`PackError`] naming what is wrong and in which stage.
    pub fn parse(text: &str) -> Result<Self, PackError> {
        let file: PackFile =
            ron::from_str(text).map_err(|error| PackError::Syntax(error.to_string()))?;
        Self::from_file(file)
    }

    /// Checks and links a pack built in code.
    ///
    /// # Errors
    /// [`PackError`] naming what is wrong and in which stage.
    pub fn from_file(file: PackFile) -> Result<Self, PackError> {
        if file.version != PACK_VERSION {
            return Err(PackError::Version {
                found: file.version,
                supported: PACK_VERSION,
            });
        }
        let mut by_name = BTreeMap::new();
        for (index, stage) in file.stages.iter().enumerate() {
            if by_name.insert(stage.name.clone(), index).is_some() {
                return Err(PackError::DuplicateName(stage.name.clone()));
            }
        }
        let outputs: Vec<Output> = file.stages.iter().map(|def| def.kind.output()).collect();
        let mut stages = Vec::with_capacity(file.stages.len());
        for def in file.stages {
            let invalid = |message: String| PackError::Invalid {
                stage: def.name.clone(),
                message,
            };
            let reads: Vec<(&str, Reach, Output)> = match &def.kind {
                StageKind::Field(expr) => {
                    expr.check().map_err(invalid)?;
                    let mut names = Vec::new();
                    expr.inputs(&mut names);
                    names
                        .into_iter()
                        .map(|name| (name, Reach::Cells(0), Output::Field))
                        .collect()
                }
                StageKind::Blur { input, radius } => {
                    vec![(input.as_str(), Reach::Cells(*radius), Output::Field)]
                }
                StageKind::Sites {
                    height,
                    region,
                    size,
                    chance,
                } => {
                    if !(1 <= size.0 && size.0 <= size.1) {
                        return Err(invalid(format!(
                            "site sizes {} to {} chunks are not a range from 1",
                            size.0, size.1
                        )));
                    }
                    if *region < size.1 + 2 {
                        return Err(invalid(format!(
                            "a region of {region} chunks cannot keep a site of {} chunks one \
                             chunk inside it",
                            size.1
                        )));
                    }
                    if !(0.0..=1.0).contains(chance) {
                        return Err(invalid(format!("chance {chance} is not between 0 and 1")));
                    }
                    // A chunk's site lies within the chunk's region, so its footprint is at most
                    // a region away.
                    vec![(height.as_str(), Reach::Chunks(*region), Output::Field)]
                }
                StageKind::Flatten {
                    height,
                    sites,
                    blend,
                } => vec![
                    (height.as_str(), Reach::Cells(0), Output::Field),
                    (sites.as_str(), Reach::Cells(*blend), Output::Sites),
                ],
                StageKind::Solve { sites, .. } => {
                    vec![(sites.as_str(), Reach::Cells(0), Output::Sites)]
                }
                StageKind::Scatter {
                    height,
                    spacing,
                    chance,
                    between,
                    max_slope,
                    avoid,
                    apart,
                    ..
                } => {
                    if *spacing == 0 {
                        return Err(invalid("a spacing of 0 cells".to_owned()));
                    }
                    if !(0.0..=1.0).contains(chance) {
                        return Err(invalid(format!("chance {chance} is not between 0 and 1")));
                    }
                    if between
                        .is_some_and(|(low, high)| low.is_nan() || high.is_nan() || low > high)
                    {
                        return Err(invalid(format!("the height range {between:?} is empty")));
                    }
                    if max_slope.is_some_and(|slope| slope.is_nan() || slope < 0.0) {
                        return Err(invalid(format!("a slope limit of {max_slope:?}")));
                    }
                    // Candidates within `apart` are judged by their own tests, which read the
                    // height one cell around them for the slope.
                    let slope = u32::from(max_slope.is_some());
                    let mut reads =
                        vec![(height.as_str(), Reach::Cells(apart + slope), Output::Field)];
                    if let Some((sites, margin)) = avoid {
                        reads.push((sites.as_str(), Reach::Cells(apart + margin), Output::Sites));
                    }
                    reads
                }
            };
            let mut inputs = Vec::with_capacity(reads.len());
            for (name, reach, expected) in reads {
                let index = *by_name.get(name).ok_or_else(|| PackError::UnknownInput {
                    stage: def.name.clone(),
                    input: name.to_owned(),
                })?;
                if outputs[index] != expected {
                    return Err(invalid(format!(
                        "it reads {name:?} as {expected:?}, but that stage produces {:?}",
                        outputs[index]
                    )));
                }
                inputs.push((index, reach));
            }
            stages.push(Stage {
                salt: salt(&def.name),
                name: def.name,
                kind: def.kind,
                inputs,
            });
        }
        let mut point_ids: BTreeMap<u16, &str> = BTreeMap::new();
        for stage in &stages {
            if let StageKind::Scatter { .. } = stage.kind
                && let Some(other) = point_ids.insert(point_stage_id(stage.salt), &stage.name)
            {
                return Err(PackError::Invalid {
                    stage: stage.name.clone(),
                    message: format!(
                        "its points' ids would share a stage number with {other:?}; rename one"
                    ),
                });
            }
        }
        let order = topological_order(&stages)?;
        Ok(Self {
            stages,
            by_name,
            order,
        })
    }

    /// What the stage named `name` does, if there is one.
    #[must_use]
    pub fn kind(&self, name: &str) -> Option<&StageKind> {
        self.index(name).map(|index| &self.stages[index].kind)
    }

    /// The stages' names, in the order the file lists them.
    pub fn stage_names(&self) -> impl Iterator<Item = &str> {
        self.stages.iter().map(|stage| stage.name.as_str())
    }

    /// How far beyond a column of `target` each stage it depends on has to be generated, in cells
    /// along the lattice's x, for chunks of `size` cells: the largest sum of reaches along any path
    /// from `target` to it. `target` itself is included, at 0. `None` if no stage is named
    /// `target`.
    #[must_use]
    pub fn reach(&self, target: &str, size: [u32; 2]) -> Option<BTreeMap<String, u32>> {
        let target = *self.by_name.get(target)?;
        let mut reach: BTreeMap<usize, u32> = BTreeMap::from([(target, 0)]);
        // Consumers come after their inputs in `order`, so walking it backwards visits every
        // consumer of a stage before the stage itself.
        for &index in self.order.iter().rev() {
            let Some(&here) = reach.get(&index) else {
                continue;
            };
            for &(input, span) in &self.stages[index].inputs {
                let there = reach.entry(input).or_insert(0);
                *there = (*there).max(here + span.cells(size)[0]);
            }
        }
        Some(
            reach
                .into_iter()
                .map(|(index, cells)| (self.stages[index].name.clone(), cells))
                .collect(),
        )
    }

    pub(crate) fn index(&self, name: &str) -> Option<usize> {
        self.by_name.get(name).copied()
    }
}

/// The stage number a Scatter stage's points carry in their ids: 15 bits of its salt, never 0,
/// which is the tiles'.
pub(crate) const fn point_stage_id(salt: u32) -> u16 {
    (salt % 0x7FFF) as u16 + 1
}

/// FNV-1a of a stage's name: the same for a stage wherever it sits in the pack, so adding or
/// reordering stages changes no other stage's random decisions.
fn salt(name: &str) -> u32 {
    name.bytes().fold(0x811C_9DC5_u32, |hash, byte| {
        (hash ^ u32::from(byte)).wrapping_mul(0x0100_0193)
    })
}

/// Stage indices with every stage after the ones it reads, or the stages of a cycle.
fn topological_order(stages: &[Stage]) -> Result<Vec<usize>, PackError> {
    #[derive(Clone, Copy, PartialEq)]
    enum Mark {
        New,
        Visiting,
        Done,
    }
    fn visit(
        index: usize,
        stages: &[Stage],
        marks: &mut [Mark],
        path: &mut Vec<usize>,
        order: &mut Vec<usize>,
    ) -> Result<(), PackError> {
        match marks[index] {
            Mark::Done => return Ok(()),
            Mark::Visiting => {
                let start = path
                    .iter()
                    .position(|&i| i == index)
                    .expect("a stage being visited is on the path");
                return Err(PackError::Cycle(
                    path[start..]
                        .iter()
                        .map(|&i| stages[i].name.clone())
                        .collect(),
                ));
            }
            Mark::New => {}
        }
        marks[index] = Mark::Visiting;
        path.push(index);
        for &(input, _) in &stages[index].inputs {
            visit(input, stages, marks, path, order)?;
        }
        path.pop();
        marks[index] = Mark::Done;
        order.push(index);
        Ok(())
    }
    let mut marks = vec![Mark::New; stages.len()];
    let mut order = Vec::with_capacity(stages.len());
    for index in 0..stages.len() {
        visit(index, stages, &mut marks, &mut Vec::new(), &mut order)?;
    }
    Ok(order)
}

#[cfg(test)]
mod tests {
    use super::*;

    const TERRAIN: &str = r#"(
        version: 1,
        stages: [
            (name: "rough", kind: Field(Noise(frequency: 0.1, octaves: 3))),
            (name: "smooth", kind: Blur(input: "rough", radius: 2)),
            (name: "height", kind: Field(Mul(Input("smooth"), Constant(8.0)))),
            (name: "softer", kind: Blur(input: "height", radius: 3)),
        ],
    )"#;

    fn pack_with(stages: &str) -> Result<Pack, PackError> {
        Pack::parse(&format!("(version: 1, stages: [{stages}])"))
    }

    #[test]
    fn a_pack_orders_each_stage_after_what_it_reads() {
        let pack = Pack::parse(TERRAIN).expect("a valid pack");

        let position = |name: &str| {
            let index = pack.index(name).expect("a stage");
            pack.order
                .iter()
                .position(|&i| i == index)
                .expect("ordered")
        };

        assert!(position("rough") < position("smooth"));
        assert!(position("smooth") < position("height"));
        assert!(position("height") < position("softer"));
    }

    #[test]
    fn reach_adds_up_along_the_longest_path() {
        let pack = Pack::parse(TERRAIN).expect("a valid pack");

        let reach = pack.reach("softer", [8, 8]).expect("a stage");

        assert_eq!(
            reach,
            BTreeMap::from([
                ("softer".to_owned(), 0),
                ("height".to_owned(), 3),
                ("smooth".to_owned(), 3),
                ("rough".to_owned(), 5),
            ])
        );
    }

    #[test]
    fn a_stage_that_reads_a_missing_one_is_named() {
        let result = pack_with(r#"(name: "a", kind: Blur(input: "nowhere", radius: 1))"#);

        assert_eq!(
            result,
            Err(PackError::UnknownInput {
                stage: "a".to_owned(),
                input: "nowhere".to_owned()
            })
        );
    }

    #[test]
    fn stages_that_read_each_other_are_a_cycle() {
        let result = pack_with(
            r#"(name: "a", kind: Blur(input: "b", radius: 1)),
               (name: "b", kind: Field(Input("a")))"#,
        );

        let Err(PackError::Cycle(stages)) = result else {
            panic!("expected a cycle, got {result:?}");
        };
        let mut stages = stages;
        stages.sort();
        assert_eq!(stages, vec!["a".to_owned(), "b".to_owned()]);
    }

    #[test]
    fn two_stages_of_one_name_are_refused() {
        let result = pack_with(
            r#"(name: "a", kind: Field(Constant(1.0))), (name: "a", kind: Field(Constant(2.0)))"#,
        );

        assert_eq!(result, Err(PackError::DuplicateName("a".to_owned())));
    }

    #[test]
    fn a_stage_reading_sites_as_a_field_is_named() {
        let result = pack_with(
            r#"(name: "h", kind: Field(Constant(1.0))),
               (name: "towns", kind: Sites(height: "h", region: 6, size: (1, 3), chance: 0.5)),
               (name: "wrong", kind: Blur(input: "towns", radius: 1))"#,
        );

        assert!(
            matches!(&result, Err(PackError::Invalid { stage, .. }) if stage == "wrong"),
            "{result:?}"
        );
    }

    #[test]
    fn a_region_too_small_for_its_sites_is_refused() {
        let result = pack_with(
            r#"(name: "h", kind: Field(Constant(1.0))),
               (name: "towns", kind: Sites(height: "h", region: 4, size: (1, 3), chance: 0.5))"#,
        );

        assert!(
            matches!(&result, Err(PackError::Invalid { stage, .. }) if stage == "towns"),
            "{result:?}"
        );
    }

    #[test]
    fn a_reach_in_chunks_counts_the_chunk_size() {
        let pack = pack_with(
            r#"(name: "h", kind: Field(Constant(1.0))),
               (name: "towns", kind: Sites(height: "h", region: 6, size: (1, 3), chance: 0.5)),
               (name: "level", kind: Flatten(height: "h", sites: "towns", blend: 4))"#,
        )
        .expect("valid");

        let reach = pack.reach("level", [8, 8]).expect("a stage");

        assert_eq!(reach["towns"], 4);
        assert_eq!(reach["h"], 4 + 6 * 8);
    }

    #[test]
    fn two_scatter_stages_whose_point_ids_would_collide_are_refused() {
        let names: Vec<String> = (0..2000).map(|i| format!("s{i}")).collect();
        let mut seen: BTreeMap<u16, &str> = BTreeMap::new();
        let (first, second) = names
            .iter()
            .find_map(|name| {
                seen.insert(point_stage_id(salt(name)), name)
                    .map(|other| (other.to_owned(), name.clone()))
            })
            .expect("15 bits collide within 2000 names");
        let scatter = |name: &str| {
            format!(r#"(name: "{name}", kind: Scatter(kind: "tree", height: "h", spacing: 4))"#)
        };

        let result = pack_with(&format!(
            r#"(name: "h", kind: Field(Constant(1.0))), {}, {}"#,
            scatter(&first),
            scatter(&second)
        ));

        assert!(
            matches!(&result, Err(PackError::Invalid { stage, .. }) if *stage == second),
            "{result:?}"
        );
    }

    #[test]
    fn another_version_is_refused() {
        let result = Pack::parse("(version: 7, stages: [])");

        assert_eq!(
            result,
            Err(PackError::Version {
                found: 7,
                supported: PACK_VERSION
            })
        );
    }

    #[test]
    fn noise_without_octaves_is_named_with_its_stage() {
        let result = pack_with(r#"(name: "n", kind: Field(Noise(frequency: 0.1, octaves: 0)))"#);

        assert!(
            matches!(&result, Err(PackError::Invalid { stage, .. }) if stage == "n"),
            "{result:?}"
        );
    }

    #[test]
    fn an_unknown_field_is_a_syntax_error() {
        let result = Pack::parse("(version: 1, stages: [], extra: 1)");

        assert!(matches!(result, Err(PackError::Syntax(_))), "{result:?}");
    }

    #[test]
    fn a_stage_keeps_its_salt_wherever_it_sits() {
        let first = pack_with(r#"(name: "a", kind: Field(Constant(1.0)))"#).expect("valid");
        let second = pack_with(
            r#"(name: "b", kind: Field(Constant(2.0))), (name: "a", kind: Field(Constant(1.0)))"#,
        )
        .expect("valid");

        let salt_of = |pack: &Pack| pack.stages[pack.index("a").expect("a")].salt;

        assert_eq!(salt_of(&first), salt_of(&second));
    }
}
